INSERT INTO regions.constituencies (constituency_name, region_name)
VALUES 
-- Ashanti Region Constituencies
       ('Asante-Akim South', 'Ashanti'),
	   ('Asawase', 'Ashanti'),
	   ('Asokwa', 'Ashanti'),
  	   ('Atwima-Kwanwoma', 'Ashanti'),
	   ('Atwima-Mponua', 'Ashanti'),
	   ('Atwima-Nwabiagya North', 'Ashanti'),
	   ('Atwima-Nwabiagya South', 'Ashanti'),
	   ('Bantama', 'Ashanti'),
	   ('Bekwai', 'Ashanti'),
	   ('Bosome-Freho', 'Ashanti'),
	   ('Bosomtwe', 'Ashanti'),
	   ('Effiduase-Asokore', 'Ashanti'),
	   ('Ejisu', 'Ashanti'),
	   ('Ejura-Sekyedumase', 'Ashanti'),
	   ('Fomena Adansi North', 'Ashanti'),
	   ('Juaben', 'Ashanti'),
	   ('Kumawu', 'Ashanti'),
	   ('Kwabre East', 'Ashanti'),
	   ('Kwadaso', 'Ashanti'),
	   ('Mampong', 'Ashanti'),
	   ('Manhyia North', 'Ashanti'),
	   ('Manhyia South', 'Ashanti'),
	   ('Manso Edubia', 'Ashanti'),
	   ('Manso Nkwanta', 'Ashanti'),
	   ('New Edubease', 'Ashanti'),
	   ('Nhyiaeso', 'Ashanti'),
	   ('Nsuta-Kwamang-Beposo', 'Ashanti'),
	   ('Obuasi East', 'Ashanti'),
	   ('Obuasi West', 'Ashanti'),
	   ('Odotobri', 'Ashanti'),
	   ('Offinso North', 'Ashanti'),
	   ('Offinso South', 'Ashanti'),
	   ('Oforikrom', 'Ashanti'),
	   ('Old Tafo', 'Ashanti'),
	   ('Sekyere Afram Plains', 'Ashanti'),
	   ('Suame', 'Ashanti'),
	   ('Subin', 'Ashanti');